import { db, tasksTable } from "@workspace/db";
import { eq } from "drizzle-orm";
import { logger } from "./logger";

export interface CodeFile {
  path: string;
  content: string;
  language: string;
}

export interface PRResult {
  prUrl: string;
  branchName: string;
  isSimulated: boolean;
  filesCommitted: number;
}

function makeBranchName(taskId: number): string {
  const ts = Date.now().toString(36);
  return `ctrl-mission-${taskId}-${ts}`;
}

export function parseCodeFiles(markdown: string): CodeFile[] {
  const files: CodeFile[] = [];

  const fileBlockRegex = /\[FILE:\s*([^\]]+)\]\s*\n```(\w*)\n([\s\S]*?)```/g;
  let match;
  while ((match = fileBlockRegex.exec(markdown)) !== null) {
    files.push({
      path: match[1].trim(),
      language: match[2] || "typescript",
      content: match[3],
    });
  }

  if (files.length === 0) {
    const codeBlockRegex = /```(?:typescript|ts|javascript|js|python|go|rust)\n([\s\S]*?)```/;
    const codeMatch = codeBlockRegex.exec(markdown);
    if (codeMatch) {
      const commitMsgMatch = /## Commit Message\s*\n`([^`]+)`/.exec(markdown);
      const suffix = commitMsgMatch
        ? commitMsgMatch[1].replace(/^feat:\s*/i, "").replace(/\s+/g, "-").toLowerCase().slice(0, 36)
        : "implementation";
      files.push({
        path: `src/${suffix}.ts`,
        language: "typescript",
        content: codeMatch[1],
      });
    }
  }

  return files;
}

async function createRealPR(
  taskId: number,
  title: string,
  body: string,
  files: CodeFile[],
  branchName: string,
): Promise<string> {
  const { Octokit } = await import("octokit");
  const token = process.env.GITHUB_TOKEN!;
  const owner = process.env.GITHUB_OWNER!;
  const repo = process.env.GITHUB_REPO!;

  const octokit = new Octokit({ auth: token });

  const { data: repoData } = await octokit.rest.repos.get({ owner, repo });
  const defaultBranch = repoData.default_branch;
  const { data: refData } = await octokit.rest.git.getRef({
    owner,
    repo,
    ref: `heads/${defaultBranch}`,
  });
  const baseSha = refData.object.sha;

  await octokit.rest.git.createRef({
    owner,
    repo,
    ref: `refs/heads/${branchName}`,
    sha: baseSha,
  });

  for (const file of files) {
    const content = Buffer.from(file.content).toString("base64");
    let existingSha: string | undefined;
    try {
      const { data } = await octokit.rest.repos.getContent({
        owner,
        repo,
        path: file.path,
        ref: branchName,
      });
      if (!Array.isArray(data) && "sha" in data) existingSha = data.sha;
    } catch {}

    await octokit.rest.repos.createOrUpdateFileContents({
      owner,
      repo,
      path: file.path,
      message: `feat(ctrl-${taskId}): add ${file.path}`,
      content,
      branch: branchName,
      ...(existingSha ? { sha: existingSha } : {}),
    });
  }

  const { data: pr } = await octokit.rest.pulls.create({
    owner,
    repo,
    title,
    body,
    head: branchName,
    base: defaultBranch,
  });

  return pr.html_url;
}

export async function mergeAgentPR(taskId: number): Promise<boolean> {
  const token = process.env.GITHUB_TOKEN;
  const owner = process.env.GITHUB_OWNER;
  const repo = process.env.GITHUB_REPO;

  try {
    const [task] = await db
      .select({ prUrl: tasksTable.prUrl, branchName: tasksTable.branchName })
      .from(tasksTable)
      .where(eq(tasksTable.id, taskId));

    if (!task?.branchName || !token || !owner || !repo) return false;

    const { Octokit } = await import("octokit");
    const octokit = new Octokit({ auth: token });

    const { data: prs } = await octokit.rest.pulls.list({
      owner,
      repo,
      head: `${owner}:${task.branchName}`,
      state: "open",
    });

    if (prs.length > 0) {
      await octokit.rest.pulls.merge({
        owner,
        repo,
        pull_number: prs[0].number,
        merge_method: "squash",
      });
      return true;
    }
  } catch (err) {
    logger.warn({ err, taskId }, "Real PR merge failed");
  }

  return false;
}

export async function createAgentPR(
  taskId: number,
  taskTitle: string,
  agentName: string,
  markdown: string,
): Promise<PRResult | null> {
  const token = process.env.GITHUB_TOKEN;
  const owner = process.env.GITHUB_OWNER;
  const repo = process.env.GITHUB_REPO;

  const files = parseCodeFiles(markdown);
  const branchName = makeBranchName(taskId);
  const title = `[CTRL] ${taskTitle} — by ${agentName}`;
  const body = [
    `## Agent Mission Report`,
    ``,
    `**Agent**: \`${agentName}\``,
    `**Task**: ${taskTitle}`,
    `**Branch**: \`${branchName}\``,
    ``,
    `---`,
    ``,
    markdown.slice(0, 1800),
    ``,
    `---`,
    `*Generated by CTRL Autonomous Agent Engine · Mission ${taskId}*`,
  ].join("\n");

  if (token && owner && repo) {
    try {
      const prUrl = await createRealPR(taskId, title, body, files, branchName);
      await db
        .update(tasksTable)
        .set({ prUrl, branchName, reviewStatus: "open" })
        .where(eq(tasksTable.id, taskId));

      logger.info({ taskId, prUrl, filesCommitted: files.length }, "GitHub PR created");
      return { prUrl, branchName, isSimulated: false, filesCommitted: files.length };
    } catch (err) {
      logger.warn({ err, taskId }, "Real GitHub PR failed — using simulated PR");
    }
  }

  const prNumber = 100 + taskId;
  const simulatedOwner = owner ?? "ctrl-station";
  const simulatedRepo = repo ?? "agent-workspace";
  const prUrl = `https://github.com/${simulatedOwner}/${simulatedRepo}/pull/${prNumber}`;

  try {
    await db
      .update(tasksTable)
      .set({ prUrl, branchName, reviewStatus: "open" })
      .where(eq(tasksTable.id, taskId));
  } catch (err) {
    logger.warn({ err }, "Failed to save simulated PR to DB");
  }

  logger.info({ taskId, prUrl, simulated: true }, "Simulated GitHub PR created");
  return { prUrl, branchName, isSimulated: true, filesCommitted: files.length };
}
