// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/landing-hero/Elevated.tsx": () => import("../components/mockups/landing-hero/Elevated.tsx"),
  "./components/mockups/landing-hero/Polished.tsx": () => import("../components/mockups/landing-hero/Polished.tsx")
};
